### ISSUE TITLE
Error loading nipca module on latest hass 0.9x

### ISSUE THREAD

**Issue by reaper7** [yottatsa/hass_nipca#1]
I found Your component today
but hass can't load nipca:

```
2019-04-15 22:47:39 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.nipca. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/home/pi/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 183, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/pi/.homeassistant/custom_components/nipca.py", line 19, in <module>
    from homeassistant.components.camera.mjpeg import CONF_MJPEG_URL, CONF_STILL_IMAGE_URL
ImportError: No module named 'homeassistant.components.camera.mjpeg'
2019-04-15 22:47:39 ERROR (MainThread) [homeassistant.loader] Unable to find component nipca
2019-04-15 22:47:42 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.nipca. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/home/pi/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 183, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/pi/.homeassistant/custom_components/nipca.py", line 19, in <module>
    from homeassistant.components.camera.mjpeg import CONF_MJPEG_URL, CONF_STILL_IMAGE_URL
ImportError: No module named 'homeassistant.components.camera.mjpeg'
2019-04-15 22:47:42 ERROR (MainThread) [homeassistant.loader] Unable to find component nipca
2019-04-15 22:47:42 ERROR (MainThread) [homeassistant.setup] Setup failed for nipca: Component not found.
```

My dlink cam works on hass as mjpeg camera with this settings:
```
- platform: mjpeg
  mjpeg_url: http://192.168.0.22/mjpeg.cgi
  still_image_url: http://192.168.0.22/image.jpg
  name: camdlink
  username: myuser
  password: mypass
  authentication: basic
```

**Comment by yottatsa** [comment]
Should be working with new version. Thanks @dave-code-ruiz for https://github.com/dave-code-ruiz/nipca.
